import com.google.zxing.BarcodeFormat;
import java.awt.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import com.google.zxing.EncodeHintType;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.oned.Code128Writer;
/* Το Προγραμμα δουελευει κανονικα στο executable τα errors σε αυτο το σημειο βγαινουν λογω εξωτερικων libraries :) */
import java.util.HashMap;
import java.util.Map;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
public class eishthria extends javax.swing.JFrame {


public static int passengers=0;
public static int i=1;
public static double distanceMILES=0;
public static double price=0;
    public eishthria() {
        initComponents();
    }
    
    public eishthria(String from,String to,String date1,int numP) throws ParseException{
       initComponents();
       passengers=numP+1;
       i=1;
       jtp1.setEnabledAt(1, false);
       dedomenapolewn pol=new dedomenapolewn();
       depflight.setText(from);
       depto.setText(to);
       depdate.setText(date1);
       airportN1.setText(pol.getPolh(from));
       airportN2.setText(pol.getPolh(from));
       airportN3.setText(pol.getPolh(from));
       airportN4.setText(pol.getPolh(from));
       airportN5.setText(pol.getPolh(to));
       airportN6.setText(pol.getPolh(to));
       airportN7.setText(pol.getPolh(to));
       airportN8.setText(pol.getPolh(to));
       time5.setText(timetogo(from,to,time1.getText()));
       time6.setText(timetogo(from,to,time2.getText()));
       time7.setText(timetogo(from,to,time3.getText()));
       time8.setText(timetogo(from,to,time4.getText()));
    }
    
    public eishthria(String from,String to,String date1, String date2,int numP) throws ParseException{
       initComponents();
       passengers=numP+1;
       i=1;
       jtp1.setEnabledAt(1, true);
       dedomenapolewn pol2=new dedomenapolewn();
       depflight.setText(from);
       depto.setText(to);
       depdate.setText(date1);
       returnflight.setText(to);
       returnto.setText(from);
       returndate.setText(date2);
       airportN1.setText(pol2.getPolh(from));
       airportN2.setText(pol2.getPolh(from));
       airportN3.setText(pol2.getPolh(from));
       airportN4.setText(pol2.getPolh(from));
       airportN5.setText(pol2.getPolh(to));
       airportN6.setText(pol2.getPolh(to));
       airportN7.setText(pol2.getPolh(to));
       airportN8.setText(pol2.getPolh(to));
       airportN21.setText(pol2.getPolh(to));
       airportN22.setText(pol2.getPolh(to));
       airportN23.setText(pol2.getPolh(to));
       airportN24.setText(pol2.getPolh(to));
       airportN25.setText(pol2.getPolh(from));
       airportN26.setText(pol2.getPolh(from));
       airportN27.setText(pol2.getPolh(from));
       airportN28.setText(pol2.getPolh(from));
       time5.setText(timetogo(from,to,time1.getText()));
       time6.setText(timetogo(from,to,time2.getText()));
       time7.setText(timetogo(from,to,time3.getText()));
       time8.setText(timetogo(from,to,time4.getText()));
       time25.setText(timetogo(to,from,time21.getText()));
       time26.setText(timetogo(to,from,time22.getText()));
       time27.setText(timetogo(to,from,time23.getText()));
       time28.setText(timetogo(to,from,time24.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtp1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        depdate = new javax.swing.JLabel();
        airportN1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        airportN5 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        airportN6 = new javax.swing.JLabel();
        time6 = new javax.swing.JLabel();
        airportN2 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time7 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        airportN3 = new javax.swing.JLabel();
        airportN7 = new javax.swing.JLabel();
        airportN8 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        time8 = new javax.swing.JLabel();
        airportN4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        depflight = new javax.swing.JLabel();
        depto = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        returnflight = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        returndate = new javax.swing.JLabel();
        airportN25 = new javax.swing.JLabel();
        time22 = new javax.swing.JLabel();
        time25 = new javax.swing.JLabel();
        time27 = new javax.swing.JLabel();
        time23 = new javax.swing.JLabel();
        airportN23 = new javax.swing.JLabel();
        airportN27 = new javax.swing.JLabel();
        airportN28 = new javax.swing.JLabel();
        time24 = new javax.swing.JLabel();
        time28 = new javax.swing.JLabel();
        airportN26 = new javax.swing.JLabel();
        airportN24 = new javax.swing.JLabel();
        airportN21 = new javax.swing.JLabel();
        time26 = new javax.swing.JLabel();
        time21 = new javax.swing.JLabel();
        airportN22 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        returnto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        mp1 = new javax.swing.JLabel();
        mp2 = new javax.swing.JLabel();
        mp3 = new javax.swing.JLabel();
        mp4 = new javax.swing.JLabel();
        mp5 = new javax.swing.JLabel();
        pickedfrom1 = new javax.swing.JLabel();
        pickedto1 = new javax.swing.JLabel();
        pickedtime1 = new javax.swing.JLabel();
        pickedtime2 = new javax.swing.JLabel();
        pickedfrom2 = new javax.swing.JLabel();
        pickedtime3 = new javax.swing.JLabel();
        pickedto2 = new javax.swing.JLabel();
        pickedtime4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        telikoeis = new javax.swing.JPanel();
        p1 = new javax.swing.JLabel();
        np1 = new javax.swing.JLabel();
        sp1 = new javax.swing.JLabel();
        idp1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        np2 = new javax.swing.JLabel();
        sp2 = new javax.swing.JLabel();
        idp2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        np3 = new javax.swing.JLabel();
        sp3 = new javax.swing.JLabel();
        idp3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        np4 = new javax.swing.JLabel();
        sp4 = new javax.swing.JLabel();
        idp4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        np5 = new javax.swing.JLabel();
        sp5 = new javax.swing.JLabel();
        idp5 = new javax.swing.JLabel();
        bar1 = new javax.swing.JLabel();
        bar2 = new javax.swing.JLabel();
        bar3 = new javax.swing.JLabel();
        bar4 = new javax.swing.JLabel();
        bar5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pricetag = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Build Your Tickets!");
        setBackground(new java.awt.Color(137, 132, 162));
        setResizable(false);

        jtp1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("All flights from:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("At:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        depdate.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        depdate.setForeground(new java.awt.Color(204, 204, 204));
        depdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(depdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 114, 25));

        airportN1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN1.setForeground(new java.awt.Color(204, 204, 204));
        airportN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, 30));

        time1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time1.setForeground(new java.awt.Color(204, 204, 204));
        time1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time1.setText("9:00");
        time1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, 56));

        airportN5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN5.setForeground(new java.awt.Color(204, 204, 204));
        airportN5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 270, 30));

        time5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time5.setForeground(new java.awt.Color(204, 204, 204));
        time5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(time5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 270, 56));

        airportN6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN6.setForeground(new java.awt.Color(204, 204, 204));
        airportN6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 270, 30));

        time6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time6.setForeground(new java.awt.Color(204, 204, 204));
        time6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(time6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 270, 56));

        airportN2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN2.setForeground(new java.awt.Color(204, 204, 204));
        airportN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, 30));

        time2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time2.setForeground(new java.awt.Color(204, 204, 204));
        time2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time2.setText("14:00");
        jPanel1.add(time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 270, 56));

        time7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time7.setForeground(new java.awt.Color(204, 204, 204));
        time7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(time7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 270, 56));

        time3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time3.setForeground(new java.awt.Color(204, 204, 204));
        time3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time3.setText("17:00");
        jPanel1.add(time3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 270, 56));

        airportN3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN3.setForeground(new java.awt.Color(204, 204, 204));
        airportN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 270, 30));

        airportN7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN7.setForeground(new java.awt.Color(204, 204, 204));
        airportN7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 270, 30));

        airportN8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN8.setForeground(new java.awt.Color(204, 204, 204));
        airportN8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 270, 30));

        time4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time4.setForeground(new java.awt.Color(204, 204, 204));
        time4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time4.setText("20:00");
        jPanel1.add(time4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 270, 56));

        time8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time8.setForeground(new java.awt.Color(204, 204, 204));
        time8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(time8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 270, 56));

        airportN4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN4.setForeground(new java.awt.Color(204, 204, 204));
        airportN4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(airportN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 270, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Select");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 109, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Select");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 109, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Select");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 109, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Select");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 109, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("To:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        depflight.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        depflight.setForeground(new java.awt.Color(204, 204, 204));
        depflight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(depflight, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 133, 26));

        depto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        depto.setForeground(new java.awt.Color(204, 204, 204));
        depto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(depto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 133, 26));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 1.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 740, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 110));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 840, 110));

        jPanel7.setBackground(new java.awt.Color(0, 102, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 840, 110));

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 840, 110));

        jtp1.addTab("Departure Flight", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("All flights from:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        returnflight.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        returnflight.setForeground(new java.awt.Color(204, 204, 204));
        returnflight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(returnflight, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 133, 26));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("At:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        returndate.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        returndate.setForeground(new java.awt.Color(204, 204, 204));
        returndate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 114, 25));

        airportN25.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN25.setForeground(new java.awt.Color(204, 204, 204));
        airportN25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 270, 30));

        time22.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time22.setForeground(new java.awt.Color(204, 204, 204));
        time22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time22.setText("12:00");
        jPanel2.add(time22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 270, 56));

        time25.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time25.setForeground(new java.awt.Color(204, 204, 204));
        time25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(time25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 270, 56));

        time27.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time27.setForeground(new java.awt.Color(204, 204, 204));
        time27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(time27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 270, 56));

        time23.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time23.setForeground(new java.awt.Color(204, 204, 204));
        time23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time23.setText("17:00");
        jPanel2.add(time23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 270, 56));

        airportN23.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN23.setForeground(new java.awt.Color(204, 204, 204));
        airportN23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 270, 30));

        airportN27.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN27.setForeground(new java.awt.Color(204, 204, 204));
        airportN27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 270, 30));

        airportN28.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN28.setForeground(new java.awt.Color(204, 204, 204));
        airportN28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 270, 30));

        time24.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time24.setForeground(new java.awt.Color(204, 204, 204));
        time24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time24.setText("20:00");
        jPanel2.add(time24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 270, 56));

        time28.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time28.setForeground(new java.awt.Color(204, 204, 204));
        time28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(time28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 270, 56));

        airportN26.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN26.setForeground(new java.awt.Color(204, 204, 204));
        airportN26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 270, 30));

        airportN24.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN24.setForeground(new java.awt.Color(204, 204, 204));
        airportN24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 270, 30));

        airportN21.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN21.setForeground(new java.awt.Color(204, 204, 204));
        airportN21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, 30));

        time26.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time26.setForeground(new java.awt.Color(204, 204, 204));
        time26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(time26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 270, 56));

        time21.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        time21.setForeground(new java.awt.Color(204, 204, 204));
        time21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time21.setText("9:00");
        time21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(time21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, 56));

        airportN22.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        airportN22.setForeground(new java.awt.Color(204, 204, 204));
        airportN22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(airportN22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Select");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 109, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Select");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 109, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Select");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 109, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Select");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 109, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("To:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        returnto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        returnto.setForeground(new java.awt.Color(204, 204, 204));
        returnto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(returnto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 133, 26));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 1.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 740, -1, -1));

        jPanel9.setBackground(new java.awt.Color(0, 102, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 110));

        jPanel10.setBackground(new java.awt.Color(0, 102, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 840, 110));

        jPanel11.setBackground(new java.awt.Color(0, 102, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 840, 110));

        jPanel12.setBackground(new java.awt.Color(0, 102, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 840, 110));

        jtp1.addTab("Return Flight", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Passenger:");

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("1");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Name:");

        name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Surname:");

        surname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        surname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Id:");

        id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Email:");

        mail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mail.setForeground(new java.awt.Color(0, 0, 0));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Next Passenger");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        msg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        msg.setForeground(new java.awt.Color(204, 204, 204));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(867, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jtp1.addTab("Passenger Details", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        mp1.setBackground(new java.awt.Color(0, 0, 0));
        mp1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mp1.setForeground(new java.awt.Color(204, 204, 204));

        mp2.setBackground(new java.awt.Color(0, 0, 0));
        mp2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mp2.setForeground(new java.awt.Color(204, 204, 204));

        mp3.setBackground(new java.awt.Color(0, 0, 0));
        mp3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mp3.setForeground(new java.awt.Color(204, 204, 204));

        mp4.setBackground(new java.awt.Color(0, 0, 0));
        mp4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mp4.setForeground(new java.awt.Color(204, 204, 204));

        mp5.setBackground(new java.awt.Color(0, 0, 0));
        mp5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mp5.setForeground(new java.awt.Color(204, 204, 204));

        pickedfrom1.setBackground(java.awt.Color.white);
        pickedfrom1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pickedfrom1.setForeground(new java.awt.Color(204, 204, 204));

        pickedto1.setBackground(java.awt.Color.white);
        pickedto1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pickedto1.setForeground(new java.awt.Color(204, 204, 204));

        pickedtime1.setBackground(java.awt.Color.white);
        pickedtime1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pickedtime1.setForeground(new java.awt.Color(204, 204, 204));

        pickedtime2.setBackground(java.awt.Color.white);
        pickedtime2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pickedtime2.setForeground(new java.awt.Color(204, 204, 204));

        pickedfrom2.setBackground(java.awt.Color.white);
        pickedfrom2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pickedfrom2.setForeground(new java.awt.Color(204, 204, 204));

        pickedtime3.setBackground(java.awt.Color.white);
        pickedtime3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pickedtime3.setForeground(new java.awt.Color(204, 204, 204));

        pickedto2.setBackground(java.awt.Color.white);
        pickedto2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pickedto2.setForeground(new java.awt.Color(204, 204, 204));

        pickedtime4.setBackground(java.awt.Color.white);
        pickedtime4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pickedtime4.setForeground(new java.awt.Color(204, 204, 204));

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Print Ticket");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        telikoeis.setBorder(new javax.swing.border.MatteBorder(null));

        p1.setBackground(java.awt.Color.white);
        p1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        p1.setForeground(new java.awt.Color(0, 0, 0));

        np1.setBackground(java.awt.Color.white);
        np1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        np1.setForeground(new java.awt.Color(0, 0, 0));

        sp1.setBackground(java.awt.Color.white);
        sp1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sp1.setForeground(new java.awt.Color(0, 0, 0));

        idp1.setBackground(java.awt.Color.white);
        idp1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        idp1.setForeground(new java.awt.Color(0, 0, 0));

        p2.setBackground(java.awt.Color.white);
        p2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        p2.setForeground(new java.awt.Color(0, 0, 0));

        np2.setBackground(java.awt.Color.white);
        np2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        np2.setForeground(new java.awt.Color(0, 0, 0));

        sp2.setBackground(java.awt.Color.white);
        sp2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sp2.setForeground(new java.awt.Color(0, 0, 0));

        idp2.setBackground(java.awt.Color.white);
        idp2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        idp2.setForeground(new java.awt.Color(0, 0, 0));

        p3.setBackground(java.awt.Color.white);
        p3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        p3.setForeground(new java.awt.Color(0, 0, 0));

        np3.setBackground(java.awt.Color.white);
        np3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        np3.setForeground(new java.awt.Color(0, 0, 0));

        sp3.setBackground(java.awt.Color.white);
        sp3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sp3.setForeground(new java.awt.Color(0, 0, 0));

        idp3.setBackground(java.awt.Color.white);
        idp3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        idp3.setForeground(new java.awt.Color(0, 0, 0));

        p4.setBackground(java.awt.Color.white);
        p4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        p4.setForeground(new java.awt.Color(0, 0, 0));

        np4.setBackground(java.awt.Color.white);
        np4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        np4.setForeground(new java.awt.Color(0, 0, 0));

        sp4.setBackground(java.awt.Color.white);
        sp4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sp4.setForeground(new java.awt.Color(0, 0, 0));

        idp4.setBackground(java.awt.Color.white);
        idp4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        idp4.setForeground(new java.awt.Color(0, 0, 0));

        p5.setBackground(java.awt.Color.white);
        p5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        p5.setForeground(new java.awt.Color(0, 0, 0));

        np5.setBackground(java.awt.Color.white);
        np5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        np5.setForeground(new java.awt.Color(0, 0, 0));

        sp5.setBackground(java.awt.Color.white);
        sp5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sp5.setForeground(new java.awt.Color(0, 0, 0));

        idp5.setBackground(java.awt.Color.white);
        idp5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        idp5.setForeground(new java.awt.Color(0, 0, 0));

        bar1.setForeground(new java.awt.Color(0, 0, 0));
        bar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bar2.setForeground(new java.awt.Color(0, 0, 0));
        bar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bar3.setForeground(new java.awt.Color(0, 0, 0));
        bar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bar4.setForeground(new java.awt.Color(0, 0, 0));
        bar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bar5.setForeground(new java.awt.Color(0, 0, 0));
        bar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout telikoeisLayout = new javax.swing.GroupLayout(telikoeis);
        telikoeis.setLayout(telikoeisLayout);
        telikoeisLayout.setHorizontalGroup(
            telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telikoeisLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(telikoeisLayout.createSequentialGroup()
                            .addComponent(np5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(telikoeisLayout.createSequentialGroup()
                            .addComponent(np4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(p4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(telikoeisLayout.createSequentialGroup()
                            .addComponent(np3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(telikoeisLayout.createSequentialGroup()
                            .addComponent(np2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(telikoeisLayout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telikoeisLayout.createSequentialGroup()
                            .addComponent(np1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idp1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telikoeisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telikoeisLayout.createSequentialGroup()
                        .addComponent(bar1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telikoeisLayout.createSequentialGroup()
                        .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bar2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telikoeisLayout.createSequentialGroup()
                        .addComponent(bar4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telikoeisLayout.createSequentialGroup()
                        .addComponent(bar5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        telikoeisLayout.setVerticalGroup(
            telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telikoeisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idp1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telikoeisLayout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(np1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(np2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(np3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(np4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telikoeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(np5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idp5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bar5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("We will update you for anything in this/these email/s:");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image 1.png"))); // NOI18N

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Thank you for flying with :");

        pricetag.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pricetag.setForeground(new java.awt.Color(204, 204, 204));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Your Total Price:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pickedtime1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pickedfrom1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(pickedfrom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(pickedtime3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(193, 193, 193)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pickedtime4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pickedtime2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pickedto2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(pickedto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mp5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                .addComponent(mp4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mp3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mp2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel17))
                            .addComponent(jLabel18)
                            .addComponent(pricetag, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(telikoeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(telikoeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickedfrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickedto1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickedtime1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickedtime2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickedfrom2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickedto2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickedtime4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickedtime3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addComponent(jLabel16)
                        .addGap(39, 39, 39)
                        .addComponent(mp1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mp2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mp3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mp4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mp5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pricetag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel17)
                        .addGap(69, 69, 69)
                        .addComponent(jButton10)
                        .addGap(57, 57, 57))))
        );

        jtp1.addTab("Your Flight Details", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setBackground(Color.ORANGE);
        jButton2.setBackground(Color.BLACK);
        jButton1.setBackground(Color.BLACK);
        jButton4.setBackground(Color.BLACK); 
        pickedfrom1.setText(airportN3.getText());
        pickedto1.setText(airportN7.getText());
        pickedtime1.setText(time3.getText());
        pickedtime2.setText(time7.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setBackground(Color.ORANGE);
        jButton2.setBackground(Color.BLACK);
        jButton3.setBackground(Color.BLACK);
        jButton4.setBackground(Color.BLACK);
        pickedfrom1.setText(airportN1.getText());
        pickedto1.setText(airportN5.getText());
        pickedtime1.setText(time1.getText());
        pickedtime2.setText(time5.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setBackground(Color.ORANGE);
        jButton1.setBackground(Color.BLACK);
        jButton3.setBackground(Color.BLACK);
        jButton4.setBackground(Color.BLACK);   
        pickedfrom1.setText(airportN2.getText());
        pickedto1.setText(airportN6.getText());
        pickedtime1.setText(time2.getText());
        pickedtime2.setText(time6.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4.setBackground(Color.ORANGE);
        jButton2.setBackground(Color.BLACK);
        jButton3.setBackground(Color.BLACK);
        jButton1.setBackground(Color.BLACK);
        pickedfrom1.setText(airportN4.getText());
        pickedto1.setText(airportN8.getText());
        pickedtime1.setText(time4.getText());
        pickedtime2.setText(time8.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton5.setBackground(Color.ORANGE);
        jButton6.setBackground(Color.BLACK);
        jButton7.setBackground(Color.BLACK);
        jButton8.setBackground(Color.BLACK);
        pickedfrom2.setText(airportN21.getText());
        pickedto2.setText(airportN25.getText());
        pickedtime3.setText(time21.getText());
        pickedtime4.setText(time25.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setBackground(Color.ORANGE);
        jButton5.setBackground(Color.BLACK);
        jButton7.setBackground(Color.BLACK);
        jButton8.setBackground(Color.BLACK);
        pickedfrom2.setText(airportN22.getText());
        pickedto2.setText(airportN26.getText());
        pickedtime3.setText(time22.getText());
        pickedtime4.setText(time26.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setBackground(Color.ORANGE);
        jButton5.setBackground(Color.BLACK);
        jButton6.setBackground(Color.BLACK);
        jButton8.setBackground(Color.BLACK);
        pickedfrom2.setText(airportN23.getText());
        pickedto2.setText(airportN27.getText());
        pickedtime3.setText(time23.getText());
        pickedtime4.setText(time27.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jButton8.setBackground(Color.ORANGE);
        jButton5.setBackground(Color.BLACK);
        jButton6.setBackground(Color.BLACK);
        jButton7.setBackground(Color.BLACK);
        pickedfrom2.setText(airportN24.getText());
        pickedto2.setText(airportN28.getText());
        pickedtime3.setText(time24.getText());
        pickedtime4.setText(time28.getText());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        if(name.getText().trim().isEmpty() || surname.getText().trim().isEmpty() || id.getText().trim().isEmpty()|| mail.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null, "one field is empty");}
        else{
        if(i==1){
           p1.setText("Passenger 1:");
           np1.setText(name.getText());
           sp1.setText(surname.getText());
           idp1.setText(id.getText());
           mp1.setText(mail.getText());
           String barcodeData = name.getText()+surname.getText()+id.getText();
           ImageIcon barcodeIcon = generateBarcode(barcodeData);
           bar1.setIcon(barcodeIcon);
        }
        else if(i==2){
           p2.setText("Passenger 2:");
           np2.setText(name.getText());
           sp2.setText(surname.getText());
           idp2.setText(id.getText());
           mp2.setText(mail.getText());
           String barcodeData = name.getText()+surname.getText()+id.getText();
           ImageIcon barcodeIcon = generateBarcode(barcodeData);
           bar2.setIcon(barcodeIcon);
        }else if(i==3){
           p3.setText("Passenger 3:");
           np3.setText(name.getText());
           sp3.setText(surname.getText());
           idp3.setText(id.getText());
           mp3.setText(mail.getText());
           String barcodeData = name.getText()+surname.getText()+id.getText();
           ImageIcon barcodeIcon = generateBarcode(barcodeData);
           bar3.setIcon(barcodeIcon);
        }else if(i==4){
           p4.setText("Passenger 4:");
           np4.setText(name.getText());
           sp4.setText(surname.getText());
           idp4.setText(id.getText());
           mp4.setText(mail.getText());
           String barcodeData = name.getText()+surname.getText()+id.getText();
           ImageIcon barcodeIcon = generateBarcode(barcodeData);
           bar4.setIcon(barcodeIcon);
        }else if(i==5){
           p5.setText("Passenger 5:");
           np5.setText(name.getText());
           sp5.setText(surname.getText());
           idp5.setText(id.getText());
           mp5.setText(mail.getText());
           String barcodeData = name.getText()+surname.getText()+id.getText();
           ImageIcon barcodeIcon = generateBarcode(barcodeData);
           bar5.setIcon(barcodeIcon);
        }
        i=i+1;
        price=price+calcPRICE();
        pricetag.setText(price+"€");
        if (passengers<i){
            jButton9.setEnabled(false);
            msg.setText("No more passengers to fill");}
        else{
        jLabel8.setText(String.valueOf(i));
        name.setText("");
        surname.setText("");
        id.setText("");
        mail.setText("");
        }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

            
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
 
    try {
        printRecord(telikoeis);
    } catch (PrinterException ex) {
        Logger.getLogger(eishthria.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jButton10MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eishthria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eishthria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eishthria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eishthria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new eishthria().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airportN1;
    private javax.swing.JLabel airportN2;
    private javax.swing.JLabel airportN21;
    private javax.swing.JLabel airportN22;
    private javax.swing.JLabel airportN23;
    private javax.swing.JLabel airportN24;
    private javax.swing.JLabel airportN25;
    private javax.swing.JLabel airportN26;
    private javax.swing.JLabel airportN27;
    private javax.swing.JLabel airportN28;
    private javax.swing.JLabel airportN3;
    private javax.swing.JLabel airportN4;
    private javax.swing.JLabel airportN5;
    private javax.swing.JLabel airportN6;
    private javax.swing.JLabel airportN7;
    private javax.swing.JLabel airportN8;
    private static javax.swing.JLabel bar1;
    private static javax.swing.JLabel bar2;
    private static javax.swing.JLabel bar3;
    private static javax.swing.JLabel bar4;
    private static javax.swing.JLabel bar5;
    private javax.swing.JLabel depdate;
    private javax.swing.JLabel depflight;
    private javax.swing.JLabel depto;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idp1;
    private javax.swing.JLabel idp2;
    private javax.swing.JLabel idp3;
    private javax.swing.JLabel idp4;
    private javax.swing.JLabel idp5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jtp1;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel mp1;
    private javax.swing.JLabel mp2;
    private javax.swing.JLabel mp3;
    private javax.swing.JLabel mp4;
    private javax.swing.JLabel mp5;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField name;
    private javax.swing.JLabel np1;
    private javax.swing.JLabel np2;
    private javax.swing.JLabel np3;
    private javax.swing.JLabel np4;
    private javax.swing.JLabel np5;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel pickedfrom1;
    private javax.swing.JLabel pickedfrom2;
    private javax.swing.JLabel pickedtime1;
    private javax.swing.JLabel pickedtime2;
    private javax.swing.JLabel pickedtime3;
    private javax.swing.JLabel pickedtime4;
    private javax.swing.JLabel pickedto1;
    private javax.swing.JLabel pickedto2;
    private javax.swing.JLabel pricetag;
    private javax.swing.JLabel returndate;
    private javax.swing.JLabel returnflight;
    private javax.swing.JLabel returnto;
    private javax.swing.JLabel sp1;
    private javax.swing.JLabel sp2;
    private javax.swing.JLabel sp3;
    private javax.swing.JLabel sp4;
    private javax.swing.JLabel sp5;
    private javax.swing.JTextField surname;
    private javax.swing.JPanel telikoeis;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time21;
    private javax.swing.JLabel time22;
    private javax.swing.JLabel time23;
    private javax.swing.JLabel time24;
    private javax.swing.JLabel time25;
    private javax.swing.JLabel time26;
    private javax.swing.JLabel time27;
    private javax.swing.JLabel time28;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    private javax.swing.JLabel time6;
    private javax.swing.JLabel time7;
    private javax.swing.JLabel time8;
    // End of variables declaration//GEN-END:variables
public static String timetogo(String from, String to,String time) throws ParseException{
              String[][] array ={
    {"Thessaloniki", " 40.640171018799506", "22.942192923132737"}, 
    {"Athens", "38.10596276429887", "23.758175285904912"}, 
    {"London", "51.81767570346753", "-0.8388814900734096"}, 
    {"Barcelona", "40.86343502613225", "2.3411037364301697"}, 
    {"Berlin", "52.873463339937985", "13.396144193502279"}, 
    {"Paris", "49.40758728466314", "2.2320079445855496"}, 
    {"Rome", "41.95436321950421", "13.141587340921117"}, 
    {"Istanbul", "41.274679621580056", "28.59682481906316"},
    {"New York", "40.431180850635926", "-73.84054728992075"}, 
    {"Tokyo", "34.921688495800076", "139.0031824717468"},
    {"Rio de Janeiro", "-23.764031505132447", "-42.53721543163381"}, 
};
        int k1=0;
        int h1=0;
        for(int k=0;k<11;k++){
             if(array[k][0].equalsIgnoreCase(from)){
                 k1=k;
                 break;
             }
        }
        for(int h=0;h<11;h++){
             if(array[h][0].equalsIgnoreCase(to)){
                 h1=h;
                 break;
             }
        }
        
        String s1=array[k1][1];
        String s2=array[k1][2];
        String s3=array[h1][1];
        String s4=array[h1][2];
        double x1 = Double.parseDouble(s1);
        double y1 = Double.parseDouble(s2);
        double x2 = Double.parseDouble(s3);
        double y2 = Double.parseDouble(s4);
        double theta = y1 - y2;
	double dist = Math.sin(Math.toRadians(x1)) * Math.sin(Math.toRadians(x2)) + Math.cos(Math.toRadians(x1)) * Math.cos(Math.toRadians(x2)) * Math.cos(Math.toRadians(theta));
	dist = Math.acos(dist);
	dist = Math.toDegrees(dist);
        distanceMILES=dist * 60 *1.1515;
	dist = (dist * 60 *1.1515)* 1.609344;
        dist=dist/900;
        int dint= (int)Math.round(dist);
        if(dint==0)dint++;
        String time1=dint+":00";
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
        timeFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
        Date date1 = timeFormat.parse(time1);
        Date date2 = timeFormat.parse(time);
        long sum = date1.getTime() + date2.getTime();
        String date3 = timeFormat.format(new Date(sum));
      return date3;
}
private void printRecord(JPanel panel) throws PrinterException{
      PrinterJob pj = PrinterJob.getPrinterJob();
      pj.setJobName(" Print Component ");

  pj.setPrintable (new Printable() {    
    public int print(Graphics pg, PageFormat pf, int pageNum){
      if (pageNum > 0){
      return Printable.NO_SUCH_PAGE;
      }

      Graphics2D g2 = (Graphics2D) pg;
      g2.translate(pf.getImageableX(), pf.getImageableY());
      panel.paint(g2);
      return Printable.PAGE_EXISTS;
    }
  });
  if (pj.printDialog() == false)
  return;

  try {
        pj.print();
  } catch (PrinterException ex) {
        // handle exception
  }
}
public static ImageIcon generateBarcode(String data) {
    BarcodeFormat barcodeFormat = BarcodeFormat.CODE_128;

        // Set encoding hints
        Map<EncodeHintType, Object> hints = new HashMap<>();
        hints.put(EncodeHintType.CHARACTER_SET, "UTF-8");

        // Create the BitMatrix for the barcode
        BitMatrix bitMatrix = new Code128Writer().encode(data, barcodeFormat, 300, 100, hints);
        // Convert BitMatrix to BufferedImage
        int width = bitMatrix.getWidth();
        int height = bitMatrix.getHeight();
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                image.setRGB(x, y, bitMatrix.get(x, y) ? Color.BLACK.getRGB() : Color.WHITE.getRGB());
            }
        }
        // Convert BufferedImage to ImageIcon
        ImageIcon icon = new ImageIcon(image);
        return icon;
    }
public double calcPRICE(){
   double price=distanceMILES*0.25;
   return Math.round(price);
}

}
